# Generated by Django 3.2.7 on 2021-09-13 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=5000)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%d/%m/%Y')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_net_name', models.CharField(choices=[('pers_website', 'WebSite'), ('mail', 'Mail'), ('telegram', 'Telegram'), ('git', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('insta', 'Instagram'), ('vk', 'VKontakte'), ('linkin', 'LindkedIn')], default='', max_length=20)),
                ('url', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='user_account.userprofile')),
            ],
        ),
    ]
