# Generated by Django 3.2.6 on 2021-08-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_delete_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_service_name', models.CharField(choices=[('pers_website', 'WebSite'), ('git', 'GitHub'), ('facebook', 'FaceBook'), ('twitter', 'Twitter'), ('insta', 'Instagram')], max_length=20)),
                ('url', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='user_account.userprofile')),
            ],
        ),
    ]
