# Generated by Django 3.2.6 on 2021-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='social_service_name',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='social_net_name',
            field=models.CharField(choices=[('pers_website', 'WebSite'), ('telegram', 'Telegram'), ('git', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('insta', 'Instagram'), ('vk', 'VKontakte'), ('linkin', 'LindkedIn')], default='', max_length=20),
        ),
    ]
