# Generated by Django 3.2.6 on 2021-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20210827_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='social_net_name',
            field=models.CharField(choices=[('pers_website', 'WebSite'), ('mail', 'Mail'), ('telegram', 'Telegram'), ('git', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('insta', 'Instagram'), ('vk', 'VKontakte'), ('linkin', 'LindkedIn')], default='', max_length=20),
        ),
    ]
